### ISSUE TITLE
Criar servidor http

### ISSUE THREAD

**Issue by iagotito** [irisalmeida/registra_ai#3]
Para a segunda etapa, vamos pegar o programa que foi criado e evoluir ele para funcionar como um servidor, usando a biblioteca Flask.

1. Baixar o flask. Recomendo utilizar ambientes virtuais para gerenciar as bibliotecas (pesquisa sobre 'python venv'). 
```shell
pip install flask
```

Quando baixar bibliotecas, é importante registrar para manter registro do que está usando para outras pessoas poderem usar também. Para isso, é padrão em python ter o arquivo `requirements.txt` com tudo que está sendo usado. Use o comando `pip freeze` para ver todas as bibliotecas instaladas, bem como suas versões. Você pode usar o output do `pip freeze` para criar o `requirements.tst`
```shell
pip freeze > requirements.txt
```

2. Criar módulo do servidor. Vamos criar vários arquivos nesse servidor: para lidar com as requisições, lidar com manipulação de dados, lidar com o banco de dados etc. Então, vamos logo criar um diretório que vai armazenar todos esses arquivos.
2.1. - Crie um diretório. "serverregistraai" ou qualquer coisa assim.
2.2. - Transforme esse diretório em um módulo python. Isso é feito criado um arquivo `__init__.py`. O arquivo pode ficar vazio mesmo, a simples existência dele diz ao python que o diretório é um módulo.
2.3. - Crie o arquivo principal do módulo, o que vai ter o código para subir o servidor. O arquivo principal do módulo é chamado `__main__.py`. 
2.4. - Crie um arquivo chamado `rest.py`. Ele vai ter o código que vai lidar com a camada REST (pesquisa), que vai lidar com a comunicação. Nele você cria o app do flask (pesquisa) e define as rotas. 
2.5. - Uma vez com o arquivo `rest.py` pronto, importa o app no `__main__.py` e inicia o servidor (pesquisa).

Com isso, basta chamar o módulo, que vai executar o código do `__main__.py` e iniciar o sevidor.
```shell
python -m serverregistraai
```

**Comment by irisalmeida** [comment]
Fechado pelo PR #4
